version: '3'
services:
  app:
    container_name: app-geogame
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - geogame:/usr/src/app/
    depends_on:
      - postgis-geogame
    networks:
      - geogame-network
#      - new

  postgis-geogame:
    image: kartoza/postgis
    container_name: pg-geogame
    environment:
      - POSTGRES_USER=geogameuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=geo_game_db
#      - DATABASE_HOST=127.0.0.1
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - geogame-network
#      new:
#        aliases:
#          - database
  migrate:
    image: migrate/migrate
    restart: on-failure
    networks:
      - geogame-network
#      - new
    volumes:
      - $PWD/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://geogameuser:password@postgis-geogame:5432/geo_game_db?sslmode=disable", "up", "3"]
    depends_on:
      - postgis-geogame
    links:
      - postgis-geogame
volumes:
  geogame:
  database_postgres:
networks:
#  new:
  geogame-network:
    driver: bridge