version: '3'
services:
  app:
    container_name: app-geogame
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - geogame:/usr/src/app/
    depends_on:
      - postgis-geogame
    networks:
      - geogame-network
    links:
      - postgis-geogame

  postgis-geogame:
    image: kartoza/postgis
    container_name: pg_geogame
    environment:
      - POSTGRES_USER=geogameuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=geo_game_db
      - DATABASE_HOST=localhost
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - geogame-network

volumes:
  geogame:
  database_postgres:
networks:
  geogame-network:
    driver:
      bridge
